// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PidzhaWEB.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Pidzha.Domain.Discipline", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ExamTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Hours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.HasIndex("ExamTypeID");

                    b.HasIndex("TeacherName");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("Pidzha.Domain.ExamType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ExamTypes");
                });

            modelBuilder.Entity("Pidzha.Domain.Teacher", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Pidzha.Domain.Discipline", b =>
                {
                    b.HasOne("Pidzha.Domain.ExamType", null)
                        .WithMany("TypeToGG")
                        .HasForeignKey("ExamTypeID");

                    b.HasOne("Pidzha.Domain.Teacher", "Teacher")
                        .WithMany("TaughtDisciplines")
                        .HasForeignKey("TeacherName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Pidzha.Domain.ExamType", b =>
                {
                    b.Navigation("TypeToGG");
                });

            modelBuilder.Entity("Pidzha.Domain.Teacher", b =>
                {
                    b.Navigation("TaughtDisciplines");
                });
#pragma warning restore 612, 618
        }
    }
}
